### PR TITLE
Replace Google Maps with Leaflet and remove filter dropdown.

### PR DESCRIPTION
**Pull request by aelawson**
Marker logic and clustering is preserved. As discussed during the last meetup, the filter dropdown was also removed - this means the map will fetch all incidents for all cities by default. Once we implement the viewport-based rendering / caching, this shouldn't become an issue as the app scales.

### CODE REVIEW

**Comment by aelawson** [comment]
Let me know what you think!

**Comment by aelawson** [comment]
Also, the Leaflet clustering engine renders geo-boundaries if you hover over each cluster - looks pretty sleek!

**Comment by AlexMerritt** [comment]
It is looking good. I just went though and re-factored the mappy-ctrl.js and move all of the map related instance to their own service(map.js). This let we set up events and check lat, lng, and zoom levels. It's almost all ready to be plugged into the new database. There is a little bit more refactoring of mappy-ctrl.js but for now it is working better. The only issues that I am having is getting the markers to be displayed with you clicked on them. I have the event you put there but it's not really returning anything of value but I don't think it will be that much work to figure out.

**Comment by aelawson** [comment]
Awesome, looks nice! Yeah, I don't think the click events on markers have worked for some time. I made an issue - I'll can see if I can fix that.

**Pull request merged**
